<a href="https://colab.research.google.com/github/vickdurazzo/python_numpy/blob/main/Python_para_Analise_de_dados_Numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Python para Análise de Dados - Numpy**

In [ ]:
# Importando biblioteca numpy
import numpy as np

In [ ]:
# Criando um array de 1 dimensão
one_dim = np.array([1,2,3,4])

In [ ]:
type(one_dim)

numpy.ndarray

In [ ]:
# Imprimindo as dimensões do array
one_dim.ndim

1

In [ ]:
# Criando um array de 2 dimensões
two_dim = np.array([(1,2,3),(4,5,6)])

In [ ]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Cria um array de números aleatórios
np.random.random((5,2))

array([[0.94363932, 0.00815302],
       [0.85102426, 0.68305466],
       [0.23181616, 0.40491806],
       [0.79890216, 0.23550332],
       [0.78686082, 0.01712249]])

In [ ]:
# Cria um array com valores esparsos iniciando com o valor 10, menor que 50 e incrementando de 5 em 5
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
# Cria um array linear de 0 a 2 de no máximo 9 elementos
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# Cria um array de valores zero
# Cria um array com 3 linhas e 4 dimensões
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# **Numpy Arrays Vs Listas**


*   Arrays Numpy permitem fazermos operações em arrays inteiros de forma rápida
*   Listas não permitem operações em todos os elementos da lista
* Para operações em todos os elementos é preciso interar sobre toda a lista
* Listas em Python armazenam diferentes tipos de objetos
* Arrays Numpy considera todos os elementos de tipos distintos como strings




In [ ]:
# Lista em Python
lista = [1,2,3]

In [ ]:
# Multiplicar valores da lista por 2
lista * 2

[1, 2, 3, 1, 2, 3]

In [ ]:
# Transforme a variável da lista em um array numpy
lista = np.array(lista)

In [ ]:
# Imprimindo tipo de objeto
type(lista)

numpy.ndarray

In [ ]:
# Multiplicando cada elemento por 2
lista*2

array([2, 4, 6])

In [ ]:
# Calcular IMC de pessoas
pesos=[67,81,120,90]
altura = [1.68,1.70,1.75,1.85]

In [ ]:
# Calculo usando as listas
pesos / altura ** 2

TypeError: ignored

In [ ]:
# Transformando em arrays numpy
pesos = np.array(pesos)
altura = np.array(altura)

In [ ]:
# Calculo usando arrays numpy
pesos / altura ** 2

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

In [ ]:
# Arrays Numpy armazena elementos como strins quando estes não são inteiros ou float
a = np.array([1,3,'Casa',True])

In [ ]:
# Transforma todos os elementos em strings
a

array(['1', '3', 'Casa', 'True'], dtype='<U21')

In [ ]:
a*2

UFuncTypeError: ignored

# **Métodos e Atributos Úteis**

In [ ]:
# Retorna a forma do array no formato linhas e colunas
two_dim.shape

(2, 3)

In [ ]:
# Retorna a quantidade de dimensões
two_dim.ndim

2

In [ ]:
# Valor máximo do array
two_dim.max()

6

In [ ]:
# Valor mínimo do array
two_dim.min()

1

In [ ]:
# Imprimindo o valor médio
two_dim.mean()

3.5

In [ ]:
# Desvio padrão
two_dim.std()

1.707825127659933

In [ ]:
# tamanho
two_dim.size

6

In [ ]:
# mostra a quantidade em byte dos itens
two_dim.itemsize

8

In [ ]:
# Soma todos os elementos do array
two_dim.sum

<function ndarray.sum>

# **Tranformando Arrays**

In [ ]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Gera a Transposta da Matriz (linha -> coluna)
two_dim.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Transforma em uma matriz de uma linha
two_dim.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [ ]:
tree = np.random.random((5,3))

In [ ]:
tree.shape

(5, 3)

In [ ]:
# Transforma em uma matriz com 3 linhas e 5 colunas
tree.reshape(3,5).shape

(3, 5)

In [ ]:
tree.reshape(-1).shape

(15,)

In [ ]:
t = tree.reshape(1,15)
t.shape



(1, 15)

In [ ]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Adicionando elementos no array
two_dim = np.insert(two_dim,0,10)

In [ ]:
# A adição do elemento transforma em um array de uma linha
two_dim

array([10,  1,  2,  3,  4,  5,  6])

In [ ]:
# Apagando um elemento do array
two_dim = np.delete(two_dim,[0])

In [ ]:
two_dim

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Gerando um arquivo .txt a partir de um array
np.savetxt("dataset_array.txt",two_dim,delimiter=',')

# **Acessando Dimensões no Array**

In [ ]:
import numpy as np

In [ ]:
my_array = np.random.random([10,2])

In [ ]:
my_array

array([[0.66960202, 0.08921388],
       [0.61871998, 0.98863839],
       [0.25091596, 0.8105074 ],
       [0.13696411, 0.14854687],
       [0.46855595, 0.4334927 ],
       [0.49343611, 0.14656783],
       [0.50396426, 0.07981521],
       [0.98888685, 0.15173355],
       [0.17743224, 0.57475147],
       [0.27013969, 0.18167786]])

In [ ]:
# Imprimindo primeiro elemento
my_array[0]

array([0.66960202, 0.08921388])

In [ ]:
# Primeiro elemento da primeira coluna
my_array[0][0]

0.6696020178179571

In [ ]:
# Primeiro elemento da segunda coluna
my_array[0][1]

0.08921387833353966

In [ ]:
# Segundo elemento da segunda coluna
my_array[1][1]

0.9886383880250562

In [ ]:
# Outra forma de acessar
my_array[1,1]

0.9886383880250562

In [ ]:
# Até 3 elementos da segunda coluna
my_array[:3,1]

array([0.08921388, 0.98863839, 0.8105074 ])

In [ ]:
# Todas as linhas da segunda coluna e *10

In [ ]:
my_array[:,1]*10

array([0.89213878, 9.88638388, 8.10507402, 1.48546875, 4.33492698,
       1.46567827, 0.79815214, 1.51733546, 5.74751468, 1.8167786 ])

In [ ]:
# Comparação
my_array > 0.50

array([[ True, False],
       [ True,  True],
       [False,  True],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [ True, False],
       [False,  True],
       [False, False]])

In [ ]:
# Acessando valores por índices
my_array[my_array > 0.50]

array([0.66960202, 0.61871998, 0.98863839, 0.8105074 , 0.50396426,
       0.98888685, 0.57475147])

# **Carregar Arrays Numpy a partir de arquivos de Texto**

In [ ]:
import numpy as np

In [ ]:
# Lendo um arquivo do tipo .txt
dataset = np.loadtxt('dataset_array.txt',delimiter=',')

In [ ]:
dataset.shape

(6,)

In [ ]:
dataset

array([1., 2., 3., 4., 5., 6.])

In [ ]:
# carregando um arquivo dividido em 3 arrays, por isso o parametro unpack
a,b,c = np.loadtxt('dataset_valores.txt',skiprows=1,unpack=True)

In [ ]:
# Array a 
a

array([0.4839, 0.1292, 0.1781, 0.7676, 0.5993])

In [ ]:
# Array B
b

array([0.4536, 0.6875, 0.3049, 0.5801, 0.4357])

In [ ]:
# Array C
c

array([0.3561, 0.6565, 0.8928, 0.2038, 0.741 ])

In [ ]:
# Carrega o arquivo ignorando mais de 1 linha e preenchendo valores vazios por 0
dataset = np.genfromtxt('dataset_valores_vazio.txt',skip_header=2,filling_values=0)

In [ ]:
dataset

array([[0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875, 0.    ],
       [0.1781, 0.3049, 0.8928],
       [0.    , 0.5801, 0.2038],
       [0.5993, 0.4357, 0.741 ]])